/*유저테이블*/
CREATE TABLE DOLZI."USER" (
	ID VARCHAR2(20) NOT NULL,
	PW VARCHAR2(100) NOT NULL,
	REG_DT TIMESTAMP NOT NULL,
	MOD_DT TIMESTAMP,
	REG_BY VARCHAR2(20) NOT NULL,
	MOD_BY VARCHAR2(20),
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);
COMMENT ON TABLE DOLZI."USER" IS '유저정보';
COMMENT ON COLUMN DOLZI."USER".ID IS '아이디';
COMMENT ON COLUMN DOLZI."USER".PW IS '패스워드';
COMMENT ON COLUMN DOLZI."USER".REG_DT IS '등록시간';
COMMENT ON COLUMN DOLZI."USER".MOD_DT IS '수정시간';
COMMENT ON COLUMN DOLZI."USER".REG_BY IS '등록자';
COMMENT ON COLUMN DOLZI."USER".MOD_BY IS '수정자';